# Stage 1: build the static frontend if it exists yet (Claude Code creates it in phase 2);
# until then a one-line placeholder keeps the image and the smoke test valid.
FROM node:22-slim AS web
WORKDIR /web
COPY frontend/ ./
RUN if [ -f package.json ]; then npm ci && npm run build; else mkdir -p out && echo "StudioFace" > out/index.html; fi

# Stage 2: the API, serving the frontend from /srv/static
FROM python:3.12-slim
WORKDIR /srv
COPY pyproject.toml requirements.lock ./
COPY app ./app
# Two installs, and the order is the point.
#
# It used to be `pip install .` against a pyproject that names fastapi, stripe,
# google-cloud-storage and eight more WITHOUT VERSIONS. Every build resolved afresh: two
# deploys an hour apart could ship different code, and a compromised release of any
# direct or transitive dependency would land in production on the next push.
#
# requirements.lock pins all 50 packages with 1011 sha256 hashes, generated by
# `uv pip compile --generate-hashes --python-platform linux`. --require-hashes makes pip
# refuse anything whose artifact does not match, so a yanked, re-uploaded or tampered
# package fails the build instead of shipping.
#
# --no-deps on the second line keeps the lock authoritative: without it, installing the
# project re-resolves its own dependencies and quietly walks around everything above.
RUN pip install --no-cache-dir --require-hashes -r requirements.lock  && pip install --no-cache-dir --no-deps .
COPY --from=web /web/out ./static
ENV PORT=8080 STATIC_DIR=/srv/static
CMD ["sh", "-c", "uvicorn app.entry:app --host 0.0.0.0 --port ${PORT}"]
