# Stage 1: build the static frontend if it exists yet (Claude Code creates it in phase 2);
# until then a one-line placeholder keeps the image and the smoke test valid.
FROM node:22-slim AS web
WORKDIR /web
COPY frontend/ ./
RUN if [ -f package.json ]; then npm ci && npm run build; else mkdir -p out && echo "StudioFace" > out/index.html; fi

# Stage 2: the API, serving the frontend from /srv/static
FROM python:3.12-slim
WORKDIR /srv
COPY pyproject.toml requirements.lock ./
COPY app ./app
# Two installs, and the order is the point.
#
# It used to be `pip install .` against a pyproject that names fastapi, stripe,
# google-cloud-storage and eight more WITHOUT VERSIONS. Every build resolved afresh: two
# deploys an hour apart could ship different code, and a compromised release of any
# direct or transitive dependency would land in production on the next push.
#
# requirements.lock pins all 50 packages with 1011 sha256 hashes, generated by
# `uv pip compile --generate-hashes --python-platform linux`. --require-hashes makes pip
# refuse anything whose artifact does not match, so a yanked, re-uploaded or tampered
# package fails the build instead of shipping.
#
# --no-deps on the second line keeps the lock authoritative: without it, installing the
# project re-resolves its own dependencies and quietly walks around everything above.
RUN pip install --no-cache-dir --require-hashes -r requirements.lock  && pip install --no-cache-dir --no-deps .
COPY --from=web /web/out ./static
ENV PORT=8080 STATIC_DIR=/srv/static
# Cloud Run terminates TLS itself and proxies the request to the container as plain
# HTTP/1, naming the real scheme in X-Forwarded-Proto (Google's own container-contract
# and triggering/https-request pages, docs/verified.md 13b). uvicorn's --proxy-headers
# is already the CLI default (uvicorn/main.py), but it only reads that header from a
# connecting address in --forwarded-allow-ips, which itself defaults to 127.0.0.1,::1
# (uvicorn's own docs/settings.md, docs/verified.md 13a) - never Cloud Run's address -
# so the header was always ignored and Starlette built redirects from the literal
# (plain-http) connection scheme instead. Both flags are named explicitly so the
# second one is not a silent no-op.
#
# "*" trusts every connecting address. Google does NOT publish a fixed source-IP range
# for Cloud Run's internal proxy to pin here instead (checked and found absent,
# docs/verified.md 13c) - this is our own inference from the ingress path Google does
# document (GFE -> HTTP proxy -> app server, securing/security), not a vendor claim:
# nothing reaches this container except through that path, so there is no untrusted
# caller for a narrower list to exclude.
CMD ["sh", "-c", "uvicorn app.entry:app --host 0.0.0.0 --port ${PORT} --proxy-headers --forwarded-allow-ips='*'"]
