"""Task 83: the monitor has to survive being redirected.

Two defects, both found on 22 September 2026 while running the monitor for a report:

1. `scripts/morning.py | tail` died with
   `UnicodeEncodeError: 'charmap' codec can't encode character '\u2192'`.
   Piped, Python picks the console codec (cp1252 on this machine) instead of utf-8, and
   MORNING-REPORT.md is regenerated by the overnight run with whatever characters it
   likes. A monitor that only works when a human is watching the terminal is silent in
   a log, which is the one thing a monitor must never be.

2. Its own `print` output is block-buffered when piped while its subprocesses write
   straight to the file descriptor, so the gh and gcloud sections appeared ABOVE the
   headings they belong under - a reader of a saved log gets the sections attributed to
   the wrong thing.

The test runs the real script, hermetically: a copy of scripts/ in a temp root with its
own MORNING-REPORT.md, and fake `gh` and `gcloud` ahead of the real ones on PATH, so it
needs no network, no credentials and no repository state.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
ARROW = "→"
REPORT = f"performance 96 {ARROW} 98, blocking time 140ms {ARROW} 60ms\n"


def _fake_root(tmp_path: Path) -> Path:
    scripts = tmp_path / "scripts"
    scripts.mkdir()
    for name in ("morning.py", "_exec.py"):
        shutil.copy2(ROOT / "scripts" / name, scripts / name)
    (tmp_path / "MORNING-REPORT.md").write_text(REPORT, encoding="utf-8")
    return tmp_path


def _fake_tools(tmp_path: Path) -> Path:
    """`gh` and `gcloud` that answer instantly and print a line we can find."""
    binned = tmp_path / "bin"
    binned.mkdir()
    for name, said in (("gh", "FAKE-GH-RAN"), ("gcloud", "FAKE-GCLOUD-RAN")):
        if os.name == "nt":
            (binned / f"{name}.cmd").write_text(f"@echo {said}\n", encoding="ascii")
        else:
            script = binned / name
            script.write_text(f"#!/bin/sh\necho {said}\n", encoding="ascii")
            script.chmod(0o755)
    return binned


def _run(tmp_path: Path) -> subprocess.CompletedProcess:
    root = _fake_root(tmp_path)
    binned = _fake_tools(tmp_path)
    env = dict(os.environ)
    env["PATH"] = f"{binned}{os.pathsep}{env.get('PATH', '')}"
    # The whole point: the codec that broke it, forced on, with no utf-8 escape hatch.
    env["PYTHONIOENCODING"] = "cp1252"
    env.pop("PYTHONUNBUFFERED", None)
    return subprocess.run(
        [sys.executable, str(root / "scripts" / "morning.py")],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        env=env,
        timeout=120,
    )


def test_it_survives_being_captured_under_cp1252(tmp_path):
    """Must get through: captured, not a terminal, and the report is not ASCII."""
    done = _run(tmp_path)
    assert done.returncode == 0, f"stderr:\n{done.stderr}"
    assert "UnicodeEncodeError" not in done.stderr, done.stderr


def test_the_report_text_is_actually_printed(tmp_path):
    """A zero exit code with nothing printed would pass the test above and be useless."""
    done = _run(tmp_path)
    assert "blocking time" in done.stdout, done.stdout[:400]


def test_each_section_appears_under_its_own_heading(tmp_path):
    """Must be refused: output out of order. Without a flush the subprocess lines land
    above the heading that introduces them."""
    out = _run(tmp_path).stdout
    for heading, marker in (
        ("== last 3 CI/deploy runs", "FAKE-GH-RAN"),
        ("== Cloud Run", "FAKE-GCLOUD-RAN"),
    ):
        assert heading in out, out[:400]
        assert marker in out, out[:400]
        assert out.index(heading) < out.index(marker), (
            f"{marker!r} printed above {heading!r}:\n{out[:600]}"
        )


@pytest.mark.skipif(not (ROOT / "MORNING-REPORT.md").exists(), reason="no report yet")
def test_the_checked_in_report_needs_no_special_codec():
    """Nobody asked for this one. The script is now safe whatever the report contains,
    but the report that ships in the repository should still be plain enough that
    anything reading it with the system codec - an editor, a pager, a log viewer that is
    not Python - gets it right."""
    text = (ROOT / "MORNING-REPORT.md").read_text(encoding="utf-8")
    assert ARROW not in text, "MORNING-REPORT.md still carries a U+2192 arrow"
