"""Morning: what happened, what is live, what to click."""

import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _exec import resolve  # noqa: E402

# Redirected instead of shown in a terminal, Python encodes stdout with the console codec
# - cp1252 on this machine - and MORNING-REPORT.md is regenerated by the overnight run
# with whatever characters it likes. On 22 Sep 2026 that was an arrow, and the monitor
# died mid-report with UnicodeEncodeError. Replacing the arrow fixes one report; this
# fixes the monitor, which must never be the thing that goes quiet.
sys.stdout.reconfigure(encoding="utf-8")


def section(title: str) -> None:
    """Print a heading and flush it.

    Without the flush the headings sit in Python's block buffer while the subprocesses
    below write straight to the file descriptor, so a captured run shows gh and gcloud
    output ABOVE the headings that introduce them.
    """
    print(title)
    sys.stdout.flush()


ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
section("== MORNING-REPORT.md")
if os.path.exists("MORNING-REPORT.md"):
    with open("MORNING-REPORT.md", encoding="utf-8") as fh:
        print(fh.read())
else:
    print("(not written: the run stopped early; read logs/overnight.err and HANDOFF.md)")
section("\n== last 3 CI/deploy runs")
subprocess.run(resolve(["gh", "run", "list", "--limit", "3"]))
section("\n== Cloud Run")
subprocess.run(
    resolve(
        [
            "gcloud",
            "run",
            "services",
            "describe",
            "studioface-api",
            "--region",
            "europe-west1",
            "--format",
            "value(status.url,status.latestReadyRevisionName)",
        ]
    )
)
print(
    "\n== rate limit acceptance: python scripts/verify_ratelimit.py https://api.<domain> <selfie>"
)
print("== Stripe to live: python scripts/set_secret.py stripe-secret-key   (prompts hidden)")
